language: dart
addons:
  sonarcloud:
    organization: "ssimk0-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
dart:
  - stable

dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings lib
