name: validator
description: Laravel style of validation for dart
version: 1.0.0
# homepage: https://www.example.com
author: sebastiansimko <contact@sebastiansimko.sk>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  test_coverage: ^0.2.0
